version: "2"

run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  sort-order:
    - linter
    - severity
    - file

linters:
  default: none
  enable:
    - contextcheck
    - copyloopvar
    - depguard
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax # allow unless explicitly denied
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor

issues:
  max-issues-per-linter: 100
  max-same-issues: 4

formatters:
  enable:
    - gofumpt
  exclusions:
    paths:
      - vendor
