run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  sort-order:
    - linter
    - severity
    - file

linters:
  enable-all: false
  enable:
    - depguard
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused 
  fast: false

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitly denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
#          - pkg: unsafe
#            desc: "you will be punished ;)"

issues:
  exclude-use-default: true
  max-issues-per-linter: 100
  max-same-issues: 4
  new: false
  exclude-files:
    - ".+_test.go"
    - "vendor/*"
  exclude-dirs:
    - vendor
