services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
      #PGPORT: 5433 # if we want to change pg default port
    volumes:
      - ${PWD}/pg_volume/volumes/postgres:/var/lib/postgresql/data # link container folder to host machine folder
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $${POSTGRES_DB}
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # http://localhost:16686 Jaeger UI
      - "14268:14268"
      - "4317:4317"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    environment:
      DEBUG: true
      DB_PASSWORD: ${DB_PASSWORD}
      ENV_NAME: ${ENV_NAME}
      GOMEMLIMIT: "7MiB" # устанавливает общий объем памяти, которым может пользоваться Go runtime (90-95% от limit)
      GOGC: 100 # процент новой необработанной памяти кучи от живой памяти, по достижении которого будет запущена сборка мусора
    deploy:
      resources:
        limits:
          memory: 8M # абсолютное ограничение по использованию памяти в контейнере
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_started
  integration-tests:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    depends_on:
      app:
        condition: service_started
    environment:
      - HOST=app
      - PORT=8000